import pygame


class Cell(pygame.sprite.Sprite):
    def __init__(self, x, y, color="white"):
        super().__init__()
        self.image = pygame.Surface((30, 30))
        self.image.fill(color)
        self.rect = self.image.get_rect()
        self.rect.x = x
        self.rect.y = y


if __name__ == '__main__':
    pygame.init()
    screen = pygame.display.set_mode((450, 450))

    all_sprites = pygame.sprite.Group()
    cell = Cell(150, 0, "red")
    all_sprites.add(cell)
    cell = Cell(180, 0, "red")
    all_sprites.add(cell)
    cell = Cell(210, 0)
    all_sprites.add(cell)
    cell = Cell(240, 0)
    all_sprites.add(cell)
    cell = Cell(180, 30)
    all_sprites.add(cell)
    cell = Cell(210, 30, "pink")
    all_sprites.add(cell)
    cell = Cell(240, 30)
    all_sprites.add(cell)
    cell = Cell(180, 60)
    all_sprites.add(cell)
    cell = Cell(210, 60, "pink")
    all_sprites.add(cell)
    cell = Cell(240, 60)
    all_sprites.add(cell)
    cell = Cell(150, 90, "green")
    all_sprites.add(cell)
    cell = Cell(180, 90, "green")
    all_sprites.add(cell)
    cell = Cell(210, 90, "pink")
    all_sprites.add(cell)
    cell = Cell(240, 90, "green")
    all_sprites.add(cell)
    cell = Cell(270, 90, "green")
    all_sprites.add(cell)
    cell = Cell(180, 120)
    all_sprites.add(cell)
    cell = Cell(210, 120, "pink")
    all_sprites.add(cell)
    cell = Cell(240, 120)
    all_sprites.add(cell)
    cell = Cell(90, 150, "green")
    all_sprites.add(cell)
    cell = Cell(180, 150)
    all_sprites.add(cell)
    cell = Cell(210, 150, "pink")
    all_sprites.add(cell)
    cell = Cell(240, 150)
    all_sprites.add(cell)
    cell = Cell(330, 150, "green")
    all_sprites.add(cell)
    cell = Cell(420, 150, "red")
    all_sprites.add(cell)
    cell = Cell(0, 180)
    all_sprites.add(cell)
    cell = Cell(30, 180)
    all_sprites.add(cell)
    cell = Cell(60, 180)
    all_sprites.add(cell)
    cell = Cell(90, 180, "green")
    all_sprites.add(cell)
    cell = Cell(120, 180)
    all_sprites.add(cell)
    cell = Cell(150, 180)
    all_sprites.add(cell)
    cell = Cell(180, 180)
    all_sprites.add(cell)
    cell = Cell(210, 180, "blue")
    all_sprites.add(cell)
    cell = Cell(240, 180)
    all_sprites.add(cell)
    cell = Cell(270, 180)
    all_sprites.add(cell)
    cell = Cell(300, 180)
    all_sprites.add(cell)
    cell = Cell(330, 180, "green")
    all_sprites.add(cell)
    cell = Cell(360, 180)
    all_sprites.add(cell)
    cell = Cell(390, 180)
    all_sprites.add(cell)
    cell = Cell(420, 180, "red")
    all_sprites.add(cell)
    cell = Cell(0, 210)
    all_sprites.add(cell)
    cell = Cell(30, 210, "pink")
    all_sprites.add(cell)
    cell = Cell(60, 210, "pink")
    all_sprites.add(cell)
    cell = Cell(90, 210, "pink")
    all_sprites.add(cell)
    cell = Cell(120, 210, "pink")
    all_sprites.add(cell)
    cell = Cell(150, 210, "pink")
    all_sprites.add(cell)
    cell = Cell(180, 210, "blue")
    all_sprites.add(cell)
    cell = Cell(210, 210, "blue")
    all_sprites.add(cell)
    cell = Cell(240, 210, "blue")
    all_sprites.add(cell)
    cell = Cell(270, 210, "pink")
    all_sprites.add(cell)
    cell = Cell(300, 210, "pink")
    all_sprites.add(cell)
    cell = Cell(330, 210, "pink")
    all_sprites.add(cell)
    cell = Cell(360, 210, "pink")
    all_sprites.add(cell)
    cell = Cell(390, 210, "pink")
    all_sprites.add(cell)
    cell = Cell(420, 210)
    all_sprites.add(cell)
    cell = Cell(0, 240, "red")
    all_sprites.add(cell)
    cell = Cell(30, 240)
    all_sprites.add(cell)
    cell = Cell(60, 240)
    all_sprites.add(cell)
    cell = Cell(90, 240, "green")
    all_sprites.add(cell)
    cell = Cell(120, 240)
    all_sprites.add(cell)
    cell = Cell(150, 240)
    all_sprites.add(cell)
    cell = Cell(180, 240)
    all_sprites.add(cell)
    cell = Cell(210, 240, "blue")
    all_sprites.add(cell)
    cell = Cell(240, 240)
    all_sprites.add(cell)
    cell = Cell(270, 240)
    all_sprites.add(cell)
    cell = Cell(300, 240)
    all_sprites.add(cell)
    cell = Cell(330, 240, "green")
    all_sprites.add(cell)
    cell = Cell(360, 240)
    all_sprites.add(cell)
    cell = Cell(390, 240)
    all_sprites.add(cell)
    cell = Cell(420, 240)
    all_sprites.add(cell)
    cell = Cell(0, 270, "red")
    all_sprites.add(cell)
    cell = Cell(90, 270, "green")
    all_sprites.add(cell)
    cell = Cell(180, 270)
    all_sprites.add(cell)
    cell = Cell(210, 270, "pink")
    all_sprites.add(cell)
    cell = Cell(240, 270)
    all_sprites.add(cell)
    cell = Cell(330, 270, "green")
    all_sprites.add(cell)
    cell = Cell(180, 300)
    all_sprites.add(cell)
    cell = Cell(210, 300, "pink")
    all_sprites.add(cell)
    cell = Cell(240, 300)
    all_sprites.add(cell)
    cell = Cell(150, 330, "green")
    all_sprites.add(cell)
    cell = Cell(180, 330, "green")
    all_sprites.add(cell)
    cell = Cell(210, 330, "pink")
    all_sprites.add(cell)
    cell = Cell(240, 330, "green")
    all_sprites.add(cell)
    cell = Cell(270, 330, "green")
    all_sprites.add(cell)
    cell = Cell(180, 360)
    all_sprites.add(cell)
    cell = Cell(210, 360, "pink")
    all_sprites.add(cell)
    cell = Cell(240, 360)
    all_sprites.add(cell)
    cell = Cell(180, 390)
    all_sprites.add(cell)
    cell = Cell(210, 390, "pink")
    all_sprites.add(cell)
    cell = Cell(240, 390)
    all_sprites.add(cell)
    cell = Cell(180, 420)
    all_sprites.add(cell)
    cell = Cell(210, 420)
    all_sprites.add(cell)
    cell = Cell(240, 420, "red")
    all_sprites.add(cell)
    cell = Cell(270, 420, "red")
    all_sprites.add(cell)


    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        screen.fill("black")
        all_sprites.draw(screen)
        pygame.display.flip()

    pygame.quit()